<?php

namespace AppBundle\Entity\Repository;

/**
 * HardwareSSDReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HardwareSSDReportRepository extends \Doctrine\ORM\EntityRepository
{
}
